name: Github CI

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    
    - name: Setup Environment
      run: |
        pip install virtualenv
        virtualenv venv
        source venv/bin/activate
      
    - name: Install dependencies
      run: make install
      
    - name: Lint
      run: make lint
      
    - name: Test
      run: make test
