name: Publish to PYPI

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    name: "Publish si-photonics-toolkit to PYPI"
    steps:
      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_KEY}}
